#+STARTUP: showall indent hidestars

* Grammar

** Как построить вопрос в английском языке?

Определи время, в котором строишь вопрос. Смысловой глагол есть?
- Дa, смысловой глагол =есть=!
  Определи вспомогательный глагол для этого времени(=do=, =to be=, =have=)
  Следуй схеме:
  - вспомогательный глагол
  - подлежащее
  - cмысловой глагол
  - все остальное
  #+BEGIN_EXAMPLE
    Do you like read books?
    Have you been at school?
    Is it raining outside?
  #+END_EXAMPLE
  Если есть вопросительное слово, оно пойдет в самое начало вопроса, а
  потом опять по старой схеме:
  #+BEGIN_EXAMPLE
    Where have you been?
    How did you pass exam?
  #+END_EXAMPLE
- Нет, смыслового глагола =нет=!
  Это значит, что в утвердительном предложении используется глагол только
  =to be=, поскольку предложение в без сказуемого построить нельзя.
  В этом случае наша схема незначительно меняется:
  - Глагол to be
  - подлежащее
  - все остальное
  #+BEGIN_EXAMPLE
    Are you okay?
    Is it hot?
    Was you at home?
  #+END_EXAMPLE
  Если есть вопросительное слово, оно просто уйдет в начало:
  #+BEGIN_EXAMPLE
    What is your name?
    How old are you?
  #+END_EXAMPLE

На этом премудрости построения вопроса заканчиваются. Компоненты
всегда одни и те же, меняются только времена.

** Present Simple

Действие происходит регулярно, часто, постоянно.

Особенность: в третьем лице единственном числе к глаголу
добавляется "s" (he reads, she reads, it reads). Для простороения
вопроса или отрицания, используется вспомогательный глагол do.

Функция вспомогательных глаголов следует из названия: они помогают,
забирая на себя временную нагрузку. В случае с Present Simple
do заберет себе -s, если она есть у смыслового глагола:
#+BEGIN_EXAMPLE
  He watchs TV every evening -> He does not watch TV every evening
#+END_EXAMPLE

При построении вопроса вспомогательный глагол уйдет в начало:
#+BEGIN_EXAMPLE
Does he not watch TV every evening?
#+END_EXAMPLE

#+BEGIN_EXAMPLE
Do you like sport?
What is your name?
#+END_EXAMPLE

** Present Continuous

Действие происходит в какой-то отрезок времени, происходит какой-то процесс.

Строится: =to be= + =глагол= + =ing=

Утверждение:

#+BEGIN_EXAMPLE
  I am watching the film.
#+END_EXAMPLE

Вопрос:

#+BEGIN_EXAMPLE
  Is he watching the film?
#+END_EXAMPLE

Отрицание:

#+BEGIN_EXAMPLE
  They are not watching the film.
#+END_EXAMPLE

ВАЖНО! Устойчивая конструкция =to be= + =planing/going to= + =инфинитив глагола=.
Обозначает намерение.

#+BEGIN_EXAMPLE
  I am planning to watch the film tomorrow
  Я собираюсь посмотреть фильм завтра.
#+END_EXAMPLE

Исключения, не принимающий -ing!

#+BEGIN_EXAMPLE
    Believe - верить
    Depend - зависеть
    Belong - принадлежать
    Contain - содержать
    Forget - забывать
    Hate - ненавидеть
    Like - нравиться
    Love - любить
    Matter - иметь значение
    Need - нуждаться
    Own - владеть
    Prefer - предпочитать
    Realize - осознавать
    Remember - помнить
    Suppose - предполагать
    Want - хотеть
    Know - знать
    Mean - иметь значение
    Seem - казаться
    Understand - понимать
#+END_EXAMPLE



** Past Simple

Действие, совершившееся в прошлом.

Строится:
- Смысловой глагол правильный?
  - Да! Тогда к глаголу добавится =ed= (watched, helped etc.)
  - Нет! Тогда употребляем собственную вторую форму глагола: (see->sow, go->went etc.)

Для построения отрицания или вопроса используется вспомогательный глагол =do=. Раз он
помогает, то забирает на себя временную нагрузку: становится =did=.

Утверждение:

#+BEGIN_EXAMPLE
  I watched TV at the evening.
  I went with my dog two hours ago.
#+END_EXAMPLE

Вопрос:

#+BEGIN_EXAMPLE
  Did he went with my dog two hours ago?
#+END_EXAMPLE

Отрицание:

#+BEGIN_EXAMPLE
  I did not watch TV at the evening.
#+END_EXAMPLE

ВАЖНО! Если действие повторялось в прошлом неоднократно, используется устойчивая
конструкция =used to= + =смысловой глагол=.

#+BEGIN_EXAMPLE
  I used to wake up at 5 o'clock
  Я привык просыпаться/просыпался в пять часов.
#+END_EXAMPLE

** Past Continuous

Отличается от Present Continuous только тем, что процесс происходит в
прошлом. Раз есть вспомогательный глагол to be, он заберет на себя всю
временную нагрузку: станет was/were (were для множественного числа)

Утверждение:

#+BEGIN_EXAMPLE
  I was watching the film.
#+END_EXAMPLE

Вопрос:
#+BEGIN_EXAMPLE
  Was he watching the film?
#+END_EXAMPLE

Отрицание:

#+BEGIN_EXAMPLE
  They were not watching the film.
#+END_EXAMPLE

Исключения, не принимающие -ing!
(одинаковые с present continuous)
#+BEGIN_EXAMPLE

    Believe - верить
    Depend - зависеть
    Belong - принадлежать
    Contain - содержать
    Forget - забывать
    Hate - ненавидеть
    Like - нравиться
    Love - любить
    Matter - иметь значение
    Need - нуждаться
    Own - владеть
    Prefer - предпочитать
    Realize - осознавать
    Remember - помнить
    Suppose - предполагать
    Want - хотеть
    Know - знать
    Mean - иметь значение
    Seem - казаться
    Understand - понимать


#+END_EXAMPLE


** Present Perfect Simple

Только миг между прошлым и будущим...

В нашем случае, это миг между прошлым и настоящим.  Действие произошло так недавно в
прошлом, что имеет наипрямейшее отношение к настоящему.

Строится: =have/has= + =глагол в третьей форме=
Если глагол правильный, к нему добавится ed, если нет - вспоминаем его
третью форму.

Причем тут =has=?!

Все дело в том, что перфектов много. Нам как-то надо показать, что это именно =present
perfect=, вот мы и оставили фишечку =present simple=: к вспомогаетльному глаголу в
третьем лице единственном числе добавили =-s=. Так получился =has=.

#+BEGIN_EXAMPLE
  - Where is my dog?
  - I have seen him in the garden.
#+END_EXAMPLE

#+BEGIN_EXAMPLE
  - Has he watched this film?
  - No, he has not watched it.
#+END_EXAMPLE

 ДОПОЛНЕНИЕ! (для продвинутых):

 Есть слова-маркеры, по которым можно понять, что это будет перфект:

#+BEGIN_EXAMPLE

    ever – когда-либо, когда бы то ни было, когда-нибудь;
    never – никогда;
    just – как раз, точно, сейчас, только что и т.д.;
    already – уже
    not…yet – все еще нет, еще нет и т.д.;
    before – раньше, прежде, перед тем как;
    lately – давно, в последнее время, недавно, за последнее время;
    of late – с недавних пор, за последнее время, недавно;
    so far – к настоящему времени, на этот час, до сих пор, вплоть до этого момента;
    recently – недавно, на днях, в последнее время;
    by now – на настоящий момент;
    up to now – до сих пор, до настоящего времени.


#+END_EXAMPLE

Их противность заключается в том, что они ставятся в разное место у
предложения. Если поставить не в том место, никто не умрет, тебя все
равно поймут.

=already, lately, recently, of late= могут стоять прямо между
вспомогательным и смысловым глаголом:

#+BEGIN_EXAMPLE

He has lately seen many films. – За последнее время он посмотрел много фильмов.
I’ve already been here for an hour. – Я здесь нахожусь уже час.
He has made good progress recently. – За последнее время он добился значительного прогресса.
We haven’t spoken of late. – За последнее время мы не разговаривали.

#+END_EXAMPLE

=yet и before= уходят в конец:

#+BEGIN_EXAMPLE

I have seen this cartoon before. – Я видел этот мультфильм раньше.
He has not finished his work yet. – Он еще не закончил свою работу.

#+END_EXAMPLE

=so far, up to now, by now= могут стоять, где им вздумается: и посреди
глагола, и в самом конце, и в самом начале (лично я их встречала
редко)

#+BEGIN_EXAMPLE

He has so far written ten letters to this company.
 – К настоящему времени он уже написал в эту компанию десять писем.
Up to now I haven’t found this book. – До сих пор я не нашел эту книгу.
She has read fourteen novels by Stephen King by now.
 – На настоящий момент она прочитала четырнадцать романов Стивена Кинга.

#+END_EXAMPLE

=just, never, ever= встречаются в середине
=ever= чаще всего встречается в вопросах.

#+BEGIN_EXAMPLE

The mail has just come. – Почта только что пришла.
I have never seen him. – Я никогда его не видел.
Have you ever seen him? – Ты когда-нибудь его видел?
#+END_EXAMPLE

Как построить вопрос, если в утверждении эта гадость?
Маркер останется там, где и в утвердительном предложении. Если он
должен стоять в конце, значит, отправляем его в самый конец

#+BEGIN_EXAMPLE

Have you seen her before? - Ты видел его раньше?
Have you spoken with him of late? - Вы с ним разговаривали в последнее время?

#+END_EXAMPLE

Если он в был в середине, то в середине и останется:

#+BEGIN_EXAMPLE

Has he just finished his homework? - Он только что закончил домашнюю работу?
Have you never eaten eags? - Ты никогда не ела яйца?
#+END_EXAMPLE

Если он был в начале.. то тоже пойдет в конец (часто). Почему?
Потому что мы знаем, что вопрос в английском языке ВСЕГДА начинается
с глагола и "обогнать" глагол может только вопросительное слово. Но у
ж никак не наречие:

#+BEGIN_EXAMPLE

Has he finished his homework by now? - Он закончил домашнюю работу на настоящий момент?

#+END_EXAMPLE

 Это выглядит большим, нелогичным и раздражающим. На деле, нужно
 запомнить про =just,before,yet,never,ever,already=. Они часто
 встречаются.
