#+STARTUP: showall indent hidestars

* Упраженения 1
** Past Simple

Построить утвердительное, отрицательное и вопросительное предложение:

- I (to do) morning exercises.
  #+BEGIN_EXAMPLE
    I did morning exercieses
    I didn`t morning exercises
    Did I do morning exercises?
  #+END_EXAMPLE

- He (to work) at a factory.

- Неправильно. На данный момент твоей предложение переводится "Его
  работали на фабрике".

 Здесь не нужен глагол to be, поскольку это не консиниус, не пассивный
 залог и смысловой глагол у тебя уже есть ( work).

 Смотри в гид, который я тебе написала, а не в гугл.

 Правильно:

  #+BEGIN_EXAMPLE
    He worked at a factory
    He didn't worked at a factory
    Did he work at a factory?
  #+END_EXAMPLE

- She (to sleep) after dinner.
Последнее неправильно. Вспомогательный глагол уже стоит в прошлом
(did), значит смысловой принимает обычную форму. Потому что
вспомогательный глагол принимает весь удар (время) на себя.

  #+BEGIN_EXAMPLE
    She slept after diner
    She didn't sleep after diner
    Did She sleep after diner?
  #+END_EXAMPLE

- We (to work) part-time.
  #+BEGIN_EXAMPLE
    He worked part-time
    He didn't work part-time
    Did He work part-time?
  #+END_EXAMPLE

- They (to drink) tea every day.

Та же ошибка. Раз есть вспомогательный глагол, то смысловой
принимает обычную форму. В предыдущем же упражнении ты правильно
сделал. Проанализируй, почему.

  #+BEGIN_EXAMPLE
    They drank tea every day
    They didn't drink tea every day
    Did they drink tea every day?
  #+END_EXAMPLE

- Mike (to be) a student.
  #+BEGIN_EXAMPLE
    Mike was student
    Mike wasn't student
    Was Mike a student?
  #+END_EXAMPLE

- Helen (to have) a car.
  #+BEGIN_EXAMPLE
    Helen had a car
    Helen didn't have a car
    Did Helen have a car?
  #+END_EXAMPLE

- You (to be) a good friend.
  #+BEGIN_EXAMPLE
    You was a good friend
    You weren't a good friend
    Did you were a good friend
  #+END_EXAMPLE

  Гуглопереводчик, который я использую вместо компилятора
  подсказал мне, что что с =You= используется =Were=, чего
  не происходит, например с =Mike wasn't a good friend=.

  - гугл подсказал тебе правильно. Потому что =to be= показывает
  единственное у нас число или множественное. Поэтому
  =I am= в прошлом станет =I was=, а =you/we/they are= станет
  =you/we/they were=

- You (to be) good friends.
  #+BEGIN_EXAMPLE
   ошибка дублирования
  #+END_EXAMPLE

- It (to be) difficult to remember everything.
  #+BEGIN_EXAMPLE
    It was difficult to remember everything
    It wasn't difficult to remember everything
    Was it difficult to remember everything?
  #+END_EXAMPLE

** Past Continuous

Построить предложения в Past Continuous:

Пока что все правильно.
Подсказываю на будущее: не забудь про множественное число кое-где

- Around me people (to talk) Russian, Italian and English.
  #+BEGIN_EXAMPLE
    Around me people were talking Russian, Italian and English.
    Around me people weren't talking Russian, Italian and English.
    Were around me people talking Russian, Italian and English.
  #+END_EXAMPLE
  Исправил, т.к. =people= подразумевает множественное число

  - исправил неверно. В английском =people= - единственное число

- Arnold (to talk) to some of the other guests on the terrace when Hardy came.
  #+BEGIN_EXAMPLE
    Arnold was talking to some of the other guests on the terrace when Hardy came.
    Arnold wasn't talking to some of the other guests on the terrace when Hardy came.
    Was Arnold talking to some of the other guests on the terrace when Hardy came?
  #+END_EXAMPLE

- Alex (to look) at his watch.
  #+BEGIN_EXAMPLE
    Alex was looking at his watch
    Alex wasn't looking at his watch
    Was Alex looking at his watch?
  #+END_EXAMPLE

- All night long the stars (to glitter).
  #+BEGIN_EXAMPLE
    The stars were glittering all night long
    The stars weren't glittering all night long
    Were the stars glittering all night long?
  #+END_EXAMPLE

- Elizabeth (to eat) and didn’t raise her head.
  #+BEGIN_EXAMPLE
    Elizabeth was eating and didn't raise her head
    Elizabeth wasn't eating and didn't raise her head
    Was Elizabeth eating and didn't raise her head?
  #+END_EXAMPLE

- He drank some of the wine and ate several chunks of bread while he (to wait) for his
  dinner to come up.

  Хорошая попытка с вопросом. А теперь задай его себе по-русски:
  Он ждал ужин пока пил вино и жевал хлеб?
  В твоем варианте ты разорвал глагол и смысл потерялся.
  - Ok, понял
  #+BEGIN_EXAMPLE
    He drank some of wine and ate several chunks of bread while he was waiting for
    his dinner to come up.
    He drank some of wine and ate several chunks of bread while he wasn't waiting for
    his dinner to come up.
    Was he waiting dinner to come up, while drank some of wine and ate several chunks of bread?
  #+END_EXAMPLE

- The family (to prepare) for the party.

Семья (она, моя) - единственное число.
  #+BEGIN_EXAMPLE
    The family was preparing for the party
    The family wasn't preparing for the party
    Was the family preparing for the party?
  #+END_EXAMPLE

- She (to argue) that only Belinda knew how to treat men.
  #+BEGIN_EXAMPLE
    She was arguing that only Belinda knew how to treat men.
    She wasn't arguing that only Belinda knew how to treat men.
    Was She arguing that only Belinda knew how to treat men?
  #+END_EXAMPLE

- A few minutes later Edward (to hurry) through the streets to his bus stop.
  #+BEGIN_EXAMPLE
    A few minute later Edward was hurrying through the streets to his bus stop
    A few minute later Edward wasn't hurrying through the streets to his bus stop
    Was Edward hurrying through the streets to his bus stop a few minute later?
  #+END_EXAMPLE

- They moved across the room, which (to start) to fill up, to a vacant corner.
Та же самая ошибка, что и с =was waiting=. Смысловой глагол находится
в километре от вспомогательного, так нельзя (это же не немецкий)
Задай себе вопрос по русски: Они двигались вокруг пространства...?
 #+BEGIN_EXAMPLE
    They moved across the room, which was starting to fill up, to a vacant corner
    They moved across the room, which wasn't starting to fill up, to a vacant corner
    Did they move across the room, which was starting to fill up, to a vacant corner
  #+END_EXAMPLE

  Тут вообще-то странно, т.к. подлежащим должна быть комната, которая начинает
  заполняться?

  Думаю, здесь речь идет о пространстве.

** Present Perfect Simple

- We just … (meet) an American actor.

Подозреваю, что ты имел в виду met (мэт), но из-за правописания
употребил первую форму, а не третью.
- Да
  #+BEGIN_EXAMPLE
    We just have met an American actor
    We just haven`t met an American actor
    Have we just met an American actor?
  #+END_EXAMPLE

- Your husband … (sell) the house?
  #+BEGIN_EXAMPLE
    Your husband has sold the house
    Your husband hasn't sold the house
    Has your husband sold the house?
  #+END_EXAMPLE

- I … (not start) my new job yet.

Как изменяется правильный глагол в Перфектах? Правильно! К нему
добавляется =ed= на конце. Как и в past simple.

  #+BEGIN_EXAMPLE
    I haven't started my new job yet.
    Have i started my new job yet?
  #+END_EXAMPLE

- You … (be) to New York before?
  #+BEGIN_EXAMPLE
    Have you been to New York before?
  #+END_EXAMPLE

- Ann … (not choose) the dessert yet.
  #+BEGIN_EXAMPLE
    Ann hasn't chosen the dessert yet
    Has Ann chosen the dessert yet?
  #+END_EXAMPLE

- They … (do) the shopping today.
  #+BEGIN_EXAMPLE
    They have done the shopping today
    Have they done the shopping today?
  #+END_EXAMPLE

- Tom … ever (visit) Disneyland?
=ever= всегда будет между =have/has= и основным глаголом в
перфектах. Да, абракадабра.

  #+BEGIN_EXAMPLE
    Has Tom ever visited Disnayland?
  #+END_EXAMPLE

- I just … (see) a horror film.
С =just= та же самая гадость
  #+BEGIN_EXAMPLE
    I have just seen horror film
    Have i just  seen a horror film?
  #+END_EXAMPLE

- She … (not find) her coat.
  #+BEGIN_EXAMPLE
    She hasn't found her coat
    Has she found her coat?
  #+END_EXAMPLE

- The cat already … (eat up) the fish.

А вот =already= чаще уходит в конец, хотя
это опционально.

  #+BEGIN_EXAMPLE
    The cat has eaten the fish already.
    Has cat eaten the fish already?
  #+END_EXAMPLE

** Present Simple или Present Continuous?

- Excuse me, … you … (know) where the post office is?
  #+BEGIN_EXAMPLE
    Excuse me, do you know where the post office is?
  #+END_EXAMPLE

- I … (want) to eat a sandwich.

Технически правильно, но есть глаголы, не принимающие ing.
Want в их числе.
Так что будет просто:
  #+BEGIN_EXAMPLE
    I want to eat a sandwich.
  #+END_EXAMPLE

Неправильно.
Какой вспомогательный глагол у континиуса?
См. в гид
- … you … (go) to travel abroad next year?

Ох ты ж нифига тебе накрутил.
Собираться, планировать - это =to be + going/planing=, потом
смысловой глагол, который и показывает, что ты там собрался делать.

  #+BEGIN_EXAMPLE
    Are you going to travel abroad next year?
  #+END_EXAMPLE

- Where’s Bob? He … (listen) to music in his room.
  #+BEGIN_EXAMPLE
    Where’s Bob? He is listening music in his room.
  #+END_EXAMPLE

- How often … you …. (go) for a walk in the park?

  Это что за магический гибрид? Либо =do you go=, либо
  =are you going=, но уж никак не все вместе.

  #+BEGIN_EXAMPLE
    How often do you go for a walk in the park?
  #+END_EXAMPLE

- My father … (read) magazines very often.
  #+BEGIN_EXAMPLE
    My father reads magazines very often
  #+END_EXAMPLE

- What time … your mother … (finish) her job in the evening?

Построено грамотно, но я думаю, что здесь лучше present simple,
потому что его мама регулярно заканчивает работу по вечерам в
какое-то время.

  #+BEGIN_EXAMPLE
    What time does your mother finish her job in the evening?
  #+END_EXAMPLE

- She … (go) to the gym twice a week.

Построено грамотно. Неверное выбрано время: она ходит в зал дважды
в неделю, т.е. регулярно. Значит, present simple.

  #+BEGIN_EXAMPLE
    She goes to the gym twice a week
  #+END_EXAMPLE

- Liza … usually … (drive) to work. She usually catches the bus.

Ну, это уж совсем. =usually= - обычно. Регулярное, частое,
постоянное действие = present simple.
  #+BEGIN_EXAMPLE
    Liza doesn't usually drive to work. She usually cathces the bus
  #+END_EXAMPLE

- They … (do) their homework in the room.
  #+BEGIN_EXAMPLE
    They are doing their homework in the room
  #+END_EXAMPLE

* Упражнения 2
** Present Perfect
*** Составь утвердительное предложение из набора слов.

В гиде появилось дополнение специально для этого упражнения:

Buy/ we/ a new house
We have buy a new house

She/ their/ feed/ already/ dog
She has their feed dog already

Never/ fly / I/ a plane
I have never fly a plane

This/ read/ Anna/ already/ book
Anna has read book already

since 2010/ I/ in school / work
I have work in school since 2010

they/ all homework/ not do/ yet
They haven't do all homework yet

*** Составь вопросительную и отрицательную форму каждого предложения

He has already read this book
#+BEGIN_SRC
  Has he read this book already?
  Hi has not already read this book
#+END_SRC

They have bought a new car
#+BEGIN_SRC
  Have they bought a new car
  They haven't bought a new car
#+END_SRC

You have drunk three cups of tea today
#+BEGIN_SRC
  Have you drunk three cups of tea today
  Y haven't drunk three cups of tea today
#+END_SRC

Jane has gone to England
#+BEGIN_SRC
  Has Jane gone to England?
  Jane hasnt gone to England
#+END_SRC

Mike has lost his wallet
#+BEGIN_SRC
  Has Mike lost his wallet?
  Mike hasn't lost his wallet
#+END_SRC

Anna has visited Paris several times
#+BEGIN_SRC
  Has Anna visited Paris several times
  Anna hasn't visited Paris several times
#+END_SRC

*** Раскрой глаголы в скобках

My parents (to know) each other for many years
#+BEGIN_SRC
  My parents have known each other for many years
#+END_SRC

I (to drive) this car since 2015
#+BEGIN_SRC
  I have driven this car since 2015
#+END_SRC

We already ( to do) all the housework
#+BEGIN_SRC
  We already done all the housework
#+END_SRC

She (to close) the door
#+BEGIN_SRC
  She has closed the door
#+END_SRC

I (to read) a lot of magazines in the last few days
#+BEGIN_SRC
  I have read a lot of magasines in the last few days
#+END_SRC

Mike never (to be) to England before
#+BEGIN_SRC
  Mike never have been to England before
#+END_SRC

** Past Simple

Раскрыть скобки, употребив верную форму глагола, построить
утвердительную, вопросительную и отрицательную формы предложения

I (be) born in 1999
#+BEGIN_SRC
  I was born in 1999
  Did i born in 1999?
  I wasn't born in 1999
#+END_SRC

We (meet) 2 months ago
#+BEGIN_SRC
  We met 2 monts ago
  Did we meet 2 months ago
  We didn't mett 2 months ago
#+END_SRC

I (go) to the park at the weekend
#+BEGIN_SRC
  I went to the park at the weekend
  Did i go to the park at the weekend?
  I didn't go to the park at the weekend
#+END_SRC

I (not catch) watch you say
#+BEGIN_SRC
  I cought watch you say
  Did I catch watch you say?
  I cought not watch you say
#+END_SRC

I (become) a director 4 years ago
#+BEGIN_SRC
  I became a director 4 years ago
  Did I become a director 4 years ago?
  I didn't become a director 4 years ago
#+END_SRC

I (have) some chicken for breakfast
#+BEGIN_SRC
  I had some chicken for breakfast
  Did i have some chichen for breakfast?
  I had not some chicken for breakfast
#+END_SRC

** Неправильные глаголы:

Определить, какая форма глагола, написать перевод и все три формы:

| 1      | 2      | 3      |                    |
|--------+--------+--------+--------------------|
| Take   | Took   | Taken  | Брать              |
| Break  | Broke  | Broken | Сломать            |
| Do     | Did    | Done   | Делать             |
| Sing   | Sang   | Sung   | Петь               |
| Loose  | Lost   | Lost   | Терять/Проигрывать |
| Win    | Won    | Won    | Выигрывать         |
| Make   | Made   | Made   | Изготовлять        |
| Swim   | Swam   | Swum   | Плавать            |
| Buy    | Bought | Bought | Купить             |
| Drank  | Drank  | Drunk  | Пить               |
| Eat    | Ate    | Eaten  | Есть               |
| Fly    | Flew   | Flown  | Летать             |
| Speak  | Spoke  | Spoken | Говорить           |
| Leave  | Left   | Left   | Покидать           |
| See    | Saw    | Seen   | Видеть             |
| Wear   | Wore   | Worn   | Носить             |
| Catch  | Caught | Caught | Ловить             |
| Become | Became | Become | Становиться        |

** Present Simple или Present Continuous?

В обоих упражнениях раскрыть скобки, употребляя глаголы в нужном времени.

They (not to drink) milk now. They (to eat) an ice-cream.
#+BEGIN_SRC
  They are drinking milk now. They eating an ice-cream
#+END_SRC

I (not to drink) milk in the evening. I (not to like) it.
#+BEGIN_SRC
  I drink milk in the evening. I don't like it.
#+END_SRC

Your sister (to do) her yoga now?
#+BEGIN_SRC
  Your sister is going her yoga now?
#+END_SRC

My cousin (to go) to the gym every day.
#+BEGIN_SRC
  My cousing goes to the gym every day
#+END_SRC

Where your daughter (to work)? – She (to work) at a hospital.
#+BEGIN_SRC
  Where does your daughter works? - She works at a hospital
#+END_SRC

Their children (not to sleep) now. They (to eat) lunch.
#+BEGIN_SRC
  Their children are not speeping now. They are eating lunch.
#+END_SRC

Your father (to go) running in the morning?
#+BEGIN_SRC
  Your father goes running in the morning?
#+END_SRC

Look! The kitten (to play).
#+BEGIN_SRC
  Look. The kitten is playing
#+END_SRC

The kitten always (to play) in the evening.
#+BEGIN_SRC
  The kitten always plays in the evening
#+END_SRC

When you usually (to get) home? — I (to get) at seven o'clock.
#+BEGIN_SRC
  When do you usually get home?
#+END_SRC

His grandfather (not to work). He is retired.
#+BEGIN_SRC
  His grandfather doesn't work. He is retired.
#+END_SRC

I usually (to get) up at eight o'clock in the morning.
#+BEGIN_SRC
  I usually get up at eight o'clock in the morning
#+END_SRC

What your grandmother (to do) now? - She (to wash) her car.
#+BEGIN_SRC
  What is your grandmother doing now? - She is wasing her car.
#+END_SRC

Your sister (to study) at university? – No, she (to work) at
university.
#+BEGIN_SRC
Does your sister to study at university? - No, she works at
university
#+END_SRC

His friends (not to play) chess now. They (to play) chess at the
weekend.

#+BEGIN_SRC
His friends aren't playing chess now. They plays chess at the weekend/
#+END_SRC
